########################################################################################################
## Corpus builder for reface evaluation data
########################################################################################################
FROM ubuntu:20.04 AS corpus-builder

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN apt-get update -y && \
    apt-get install -y \
    software-properties-common && \
    add-apt-repository universe

RUN apt-get update -y && \
    apt-get install -y \
    automake \
    bash \
    bison \
    build-essential \
    coreutils \
    flex \
    git \
    gpg \
    lsb-release \
    wget \
    curl \
    python2

RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /get-pip.py && \
    python2 /get-pip.py && \
    pip2 install pycryptodome matplotlib numpy pyyaml

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc \
    | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg

RUN apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"

RUN apt-get update -y && \
    apt-get -y install cmake

COPY corpus /corpus
WORKDIR /corpus
RUN ./build.sh
COPY scripts /scripts
RUN ./extra.sh