version: '3.8'
services:
  aflplusplus:
    build:
      target: aflplusplus-builder-x86_64
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    privileged: true
    volumes:
      - ../corpus/build:/corpus
      - ../scripts/:/scripts
      - ../results/:/results

  symqemu:
    build:
      target: symqemu
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    volumes:
      - ../corpus/build:/corpus

  tfuzz:
    build:
      target: tfuzz
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    volumes:
      - ../corpus/build:/corpus

  corpus:
    build:
      target: corpus-builder
      dockerfile: ./docker/dockerfiles/Dockerfile-corpus
      context: ..
    command: bash -c 'cp -a /corpus/build/* /build/'
    volumes:
      - ../corpus/build:/build