version: '3.8'
services:
  aflplusplus:
    build:
      target: aflplusplus-corpus
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    command: python3 /scripts/aflplusplus_wrapper.py -t 1 -a /AFLplusplus/afl-fuzz -s /corpus/cgc/AIS-Lite/seeds/ -o /results/ -- /corpus/cgc/AIS-Lite/AIS-Lite
    privileged: true
    volumes:
      - ../corpus/build:/corpus
      - ../scripts/:/scripts
      - ../results/:/results
    # Remove when running at scale but good for debugging
    stdin_open: true
    tty: true


  symqemu:
    build:
      target: symqemu
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    volumes:
      - ../corpus/build:/corpus

  tfuzz:
    build:
      target: tfuzz
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    volumes:
      - ../corpus/build:/corpus

  corpus:
    build:
      target: corpus-builder
      dockerfile: ./docker/dockerfiles/Dockerfile-corpus
      context: ..
    command: bash -c '/corpus/build.sh'
    volumes:
      - ../corpus:/corpus
      - ../scripts/:/scripts/