version: '3.8'
services:
  aflplusplus:
    build:
      target: aflplusplus-corpus
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    #command: python3 aflwrapper_kube.py -t 5 -a /AFLplusplus/afl-fuzz -i ${JOB_COMPLETION_INDEX} -o /results/ -e .raw
    privileged: true
    volumes:
      - ../corpus/build:/corpus
      - ../scripts/:/scripts
      - ../results/:/results
    # Remove when running at scale but good for debugging
    stdin_open: true
    tty: true

  symqemu:
    build:
      target: symqemu
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    volumes:
      - ../corpus/build:/corpus

  tfuzz:
    build:
      target: tfuzz
      dockerfile: ./docker/dockerfiles/Dockerfile-fuzzers
      context: ..
    volumes:
      - ../corpus/build:/corpus

  corpus:
    build:
      target: corpus-builder
      dockerfile: ./docker/dockerfiles/Dockerfile-corpus
      context: ..
    command: bash -c '/corpus/build.sh; /corpus/extra.sh'
    volumes:
      - ../corpus:/corpus
      - ../scripts/:/scripts/
